name: Node.JS CI/CD

on:
  push:
    branches: ["master"]
  pull_request: 
    branches: ["master"]

jobs:
  test: 
    name: Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend/

    strategy: 
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3 # was "v2" before
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: NPM install, build and test
        run: |
          npm ci
          npm run build --if-present
          npm run test
  # Heavily modified deploy job to fit render.com
  deploy:
    name: Deploy
    needs: [test] # Our tests must pass in order to run the deploy job
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://elms-fb1g.onrender.com/api-docs

    steps:
      - name: Trigger Render Deploy
        id: trigger_deploy
        run: |
          RESPONSE=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"branch": "master"}' \
            "https://api.render.com/v1/services/${{ secrets.SERVICE_ID }}/deploys")
  
          DEPLOY_ID=$(echo $RESPONSE | jq -r '.id')
          echo "Deploy ID: $DEPLOY_ID"
          echo "::set-output name=DEPLOY_ID::${DEPLOY_ID}"
  
      - name: Check Render Deploy Status
        run: |
          while [[ "$(curl -s -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
                    -H 'Content-Type: application/json' \
                    "https://api.render.com/v1/services/${{ secrets.SERVICE_ID }}/deploys/${{ steps.trigger_deploy.outputs.DEPLOY_ID }}" | jq -r '.status')" == "build_in_progress" ]]; do
            echo "Render deploy is still in progress..."
            sleep 10
          done
