name: Node.JS CI/CD

on:
  push:
    branches: ["master"]
  pull_request: 
    branches: ["master"]

jobs:
  test: 
    name: Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend/

    strategy: 
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: NPM install, build and test
        run: |
          npm ci
          npm run build --if-present
          npm run test

  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      
