name: Node.JS CI/CD

on:
  push:
    branches: ["master"]
  pull_request: 
    branches: ["master"]

jobs:
  test: 
    name: Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend/

    strategy: 
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: NPM install, build and test
        run: |
          npm ci
          npm run build --if-present
          npm run test

  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      # Bước mới để lấy URL xem trước từ Render
      - name: Get Preview URL
        run: |
          export RENDER_PREVIEW_URL=$(curl -s https://api.render.com/v1/services/${{ secrets.SERVICE_ID }}/deploys/latest | jq -r '.serviceUrl')
          echo "RENDER_PREVIEW_URL=$RENDER_PREVIEW_URL" >> $GITHUB_ENV
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_API_KEY }}

      # Bước mới để gửi URL xem trước vào pull request
      - name: Comment Preview URL
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = 'Preview URL: ' + process.env.RENDER_PREVIEW_URL;
            await github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
            });
