name: Node.JS CI/CD

on:
  push:
    branches: ["master"]
  pull_request: 
    branches: ["master"]

jobs:
  test: 
    name: Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend/

    strategy: 
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3 # was "v2" before
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: NPM install, build and test
        run: |
          npm ci
          npm run build --if-present
          npm run test
  # Heavily modified deploy job to fit render.com
  deploy:
    name: Deploy
    needs: [test] # Our tests must pass in order to run the deploy job
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://elms-fb1g.onrender.com/api-docs

    steps:
      - name: Trigger Render Deploy
        id: trigger_deploy
        uses: johnbeynon/render-deploy-action@v0.0.8  
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
